### ISSUE TITLE
Website CSS update for linking to a title

### ISSUE THREAD

**Issue by orta** [Microsoft/TypeScript#22202]
As I cannot edit the website, I've made an issue.

With a link like: https://www.typescriptlang.org/docs/handbook/basic-types.html#tuple

I get the header cropped off by the fixed nav

![screen shot 2018-02-27 at 9 57 24 am](https://user-images.githubusercontent.com/49038/36735657-aa3c0d8a-1ba4-11e8-8307-61001db2932a.png)

If you add some code like:

```css
a[name]:before {
   display: block;
   content: '';
   margin-top: -121px;
   height: 121px;
   visibility: hidden;
}
```

Like  @Haroenv added here https://github.com/artsy/artsy.github.io/pull/301 to the Artsy blog, then you get links which will be offset, like this link: http://artsy.github.io/blog/2017/01/25/mashing-maps/#CoffeeScript
