### ISSUE TITLE
Add multiple travis test targets

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#3035]
You only have `node 0.10` as a travis test target right now. You probably should add more test targets to TS:

```yaml
language: node_js

node_js:
  - iojs
  - '0.12'
  - '0.10'

sudo: false
```
http://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Choosing-Node-versions-to-test-against
