### ISSUE TITLE
tsc command sometimes not working with Apple M1 

### ISSUE THREAD

**Issue by amoslai5128** [microsoft/TypeScript#45795]
# Bug Report

 Running ` tsc` command sometimes not working with Apple M1 in arch `arm64`
 However, windows & Linux works as expected.

## Mac
```yaml
  MacOS: Big Sur 11.5.2 (20G95)
  Model Name: MacBook Pro
  Model Identifier: MacBookPro17,1
  Chip: Apple M1
  Total Number of Cores:  8 (4 performance and 4 efficiency)
  Memory: 16 GB
  System Firmware Version: 6723.140.2
  OS Loader Version: 6723.140.2
```
## TS
- This is a crash and not perform as expected
- This is the behavior in version 4.4.2 I tried

## This is the config file:
```json
{
  "compilerOptions": {
    "module": "commonJS",
    "target": "esnext",
    "moduleResolution": "node",
    "allowJs": true,
    "checkJs": true,
    "resolveJsonModule": true,
    "declaration": true,
    "outDir": "./dist",
    "rootDir": "./src",
    "removeComments": true,
    "sourceMap": true,
    "composite": true,
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "noUncheckedIndexedAccess": true,
    "noPropertyAccessFromIndexSignature": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": [
    "./src/**/*"
  ],
  "files": [
    "./src/env.d.ts"
  ]
}
```
## This won't work:
In my .sh
```sh

build() {
    File=$1
    cd "$File"
    tsc
}

# Or 
build() {
    File=$1
    cd "$File"
    npm run build
}

// Execute function
build "/path/to/project_dir"
```
## This works:
```sh
build() {
    File=$1
    cd "$File"
    tsc
    npm run build
}
// Execute function
build "/path/to/project_dir"
```

### 🙁 Actual behavior 
Most of the time only `tsconfig.tsbuildinfo` was built.

### 🙂 Expected behavior

The project dir will build a `dist` dir after run `tsc`.
