### ISSUE TITLE
Request: Open source typescript-bot for use with other NPM packages

### ISSUE THREAD

**Issue by ctjlewis** [microsoft/TypeScript#46177]
# Suggestion

Open source [typescript-bot](https://github.com/typescript-bot) so other packages can easily use the `pack this` command.

## 🔍 Search Terms

- `typescript-bot`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

The specific package I work on frequently which would benefit from this is [Next.js](https://github.com/vercel/next.js), which has a [convoluted process](https://github.com/vercel/next.js/blob/canary/contributing.md#developing-with-your-local-version-of-nextjs) for testing your development branch.

If this team OSSes typescript-bot, this would be easily replaced with pushing up to GitHub and then asking the bot to `pack this`.

## 💻 Use Cases

- Packing a given branch of a tool to NPM for ease of development

**Comment by andrewbranch** [comment]
typescript-bot’s functionality is spread out over a bunch of places, and we don’t have the bandwidth to package it up into something for other people’s use, but I think I can point you to some of the interesting parts of it. We have an Azure Function that listens for comments, which lives here: https://github.com/weswigham/typescript-bot-test-triggerer/

For `pack this`, it runs a build defined Azure Dev Ops. We made it ages ago with the legacy UI before they went to YAML-based definitions, but I exported it to YAML and it looks like this:

```yaml
# Variable 'CI' was defined in the Variables tab
# Variable 'GH_TOKEN' was defined in the Variables tab
# Variable 'REQUESTING_USER' was defined in the Variables tab
# Variable 'SOURCE_ISSUE' was defined in the Variables tab
resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Phase_1
  displayName: Phase 1
  cancelTimeoutInMinutes: 1
  pool:
    name: Hosted Ubuntu 1604
  steps:
  - checkout: self
  - task: CmdLine@2
    displayName: Detect package-lock.json
    inputs:
      script: "if [ -f ./package-lock.json ]; then\n  echo \"##vso[task.setvariable variable=havePackageLock;]True\"\nfi\n  "
      workingDirectory: $(Build.SourcesDirectory)
  - task: Npm@1
    displayName: npm ci
    condition: and(succeeded(), eq(variables['havePackageLock'], 'True'))
    inputs:
      command: ci
      workingDir: $(Build.SourcesDirectory)
      verbose: false
  - task: Npm@1
    displayName: npm install
    condition: and(succeeded(), ne(variables['havePackageLock'], 'True'))
    inputs:
      workingDir: $(Build.SourcesDirectory)
      verbose: false
      customCommand: uninstall typescript --no-save
  - task: Npm@1
    displayName: npm update
    condition: and(succeeded(), ne(variables['havePackageLock'], 'True'))
    inputs:
      command: custom
      workingDir: $(Build.SourcesDirectory)
      verbose: false
      customCommand: update
  - task: CmdLine@2
    displayName: gulp configure-insiders LKG clean runtests-parallel
    inputs:
      script: >-
        trap "exit \$?" ERR

        gulp configure-insiders

        gulp LKG

        gulp runtests-parallel

        gulp clean
  - task: Npm@1
    displayName: npm pack ./
    inputs:
      command: custom
      verbose: false
      customCommand: pack ./
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: ./
      Contents: typescript-*.tgz
      TargetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishPipelineArtifact@0
    displayName: Publish Pipeline Artifact
    inputs:
      artifactName: tgz
      targetPath: $(Build.ArtifactStagingDirectory)
  - task: CmdLine@1
    displayName: Run comment postback
    continueOnError: True
    inputs:
      filename: node
      arguments: ./scripts/post-vsts-artifact-comment.js $(GH_TOKEN)
```

I think today, _all_ of this can be done with just GitHub Actions.
