### ISSUE TITLE
4.7 RC under `"module": "NodeNext"` not working with Yarn 3's PnP

### ISSUE THREAD

**Issue by tavoyne** [microsoft/TypeScript#49084]
# Bug Report

### 🔎 Search Terms

- 4.7
- ESM
- Node16
- NodeNext

### 🕗 Version & Regression Information

This is specific to `4.7.1-rc`.

### ⏯ Playground Link

Non applicable.

### 💻 Code

```yml
# .yarnrc.yml
nodeLinker: pnp
yarnPath: .yarn/releases/yarn-3.2.0.cjs
```
```typescript
// index.ts
import { useEffect } from "react";
```
```jsonc
// tsconfig.json
{
  "compilerOptions": {
    "module": "NodeNext"
  }
}
```
### 🙁 Actual behavior

```txt
Cannot find module 'react' or its corresponding type declarations.
```

### 🙂 Expected behavior

The import to be successful.

Switching to the `node-modules` linker fixes the problem.
