### ISSUE TITLE
Broken unicode symbol after minification

### ISSUE THREAD

**Issue by tandu** [Microsoft/TypeScript#6521]
```css
smile:before {
  content: "\200B";
}
```
Is compressed to
```css
smile:before {
  content: "200B";
}
```
https://github.com/mgechev/angular2-seed/issues/390
